fix: Update AWS role handling in auto-deploy workflow to prevent errors with default role

diff --git a/.github/workflows/auto-deploy.yaml b/.github/workflows/auto-deploy.yaml
--- a/.github/workflows/auto-deploy.yaml
+++ b/.github/workflows/auto-deploy.yaml
@@ -8,12 +8,19 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    env:
+      ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME != '' && secrets.AWS_ROLE_TO_ASSUME || 'default-role-arn' }}
     steps:
+      - name: Throw error if default role is used
+        if: ${{ env.ROLE_TO_ASSUME == 'default-role-arn' }}
+        run: |
+          echo "Error: AWS_ROLE_TO_ASSUME secret is not set. Please set it to a valid role ARN."
+          exit 1
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v5.0.0
+        uses: aws-actions/configure-aws-credentials@v5
         with:
           aws-region: ca-central-1
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} 
+          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
           role-session-name: GitHubActions
       - name: Default State Setup
         uses: ./.github/actions/default-state.action.yaml
